<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/catalog.php';
require_auth();
$user=current_user();
$stats=[];
foreach(['total'=>'SELECT COUNT(*) FROM products WHERE user_id=?','available'=>"SELECT COUNT(*) FROM products WHERE user_id=? AND status='Disponível'",'sold'=>"SELECT COUNT(*) FROM products WHERE user_id=? AND status='Vendido'",'value'=>"SELECT COALESCE(SUM(price),0) FROM products WHERE user_id=? AND status='Disponível'"] as $key=>$sql){$q=db()->prepare($sql);$q->execute([$user['id']]);$stats[$key]=$key==='value'?(float)$q->fetchColumn():(int)$q->fetchColumn();}
$q=db()->prepare("SELECT * FROM products WHERE user_id=? AND status <> 'Vendido' ORDER BY entry_date DESC,id DESC LIMIT 5");$q->execute([$user['id']]);$products=$q->fetchAll();$pageTitle='Painel';require __DIR__.'/partials/header.php';
?><section class="hero"><div class="eyebrow mb-2">Painel do brechó</div><h1>Seu acervo, com história e organização.</h1><p class="mb-0 text-muted">Acompanhe o estoque e o valor das peças disponíveis.</p></section><div class="row g-3 mb-4"><div class="col-md-3"><div class="stat-card"><div class="text-muted small">Peças cadastradas</div><div class="stat-number"><?= $stats['total'] ?></div></div></div><div class="col-md-3"><div class="stat-card"><div class="text-muted small">Disponíveis</div><div class="stat-number"><?= $stats['available'] ?></div></div></div><div class="col-md-3"><div class="stat-card"><div class="text-muted small">Vendidas</div><div class="stat-number"><?= $stats['sold'] ?></div></div></div><div class="col-md-3"><div class="stat-card"><div class="text-muted small">Valor em estoque</div><div class="stat-number">R$ <?= number_format($stats['value'],2,',','.') ?></div></div></div></div><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="page-title h4 mb-0">Últimas peças</h2><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="report.php">Relatórios</a><a class="btn btn-coral" href="clients.php?action=create">+ Nova peça</a></div></div><div class="panel p-0 overflow-hidden"><div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>Peça</th><th>Categoria</th><th>Preço</th><th>Entrada</th><th>Status</th></tr></thead><tbody><?php foreach($products as $product): ?><tr><td><span class="stock-photo"><i data-lucide="<?= e(category_icon($product['category'])) ?>"></i></span> <strong><?= e($product['code']) ?></strong><div><?= e($product['name']) ?></div></td><td><?= e($product['category']) ?></td><td>R$ <?= number_format((float)$product['price'],2,',','.') ?></td><td><?= format_date($product['entry_date']) ?></td><td><span class="status-badge <?= e(status_class($product['status'])) ?>"><?= e($product['status']) ?></span></td></tr><?php endforeach; if(!$products): ?><tr><td colspan="5" class="empty">Nenhuma peça cadastrada.</td></tr><?php endif; ?></tbody></table></div></div><?php require __DIR__.'/partials/footer.php'; ?>
